name: Auto approve
on: pull_request_target

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}