name: test-code
run-name: ${{ github.actor }} is testing his code
on: 
  push:
    branches-ignore:
      - main
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: npm install
      - run: npm run test
  create-pull-request:
    runs-on: ubuntu-latest
    needs: [run-jest-tests]
    if: ${{ needs.run-jest-tests.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Split branch name
        env: 
          BRANCH: ${{ github.ref}}
        id: split
        run: echo "::set-output name=fragment::${BRANCH##*/}"
      - run: git checkout ${{ steps.split.outputs.fragment }} 
      - run: gh pr create --base main --title 'push request' --body 'pushing latest commit, unit tests successful'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
