name: test-code
run-name: ${{ github.actor }} is testing his code
on: 
  push:
    branches-ignore:
      - main
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: npm install
      - run: npm run test
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      fragment: ${{ steps.split.outputs.fragment }}
    needs: run-jest-tests
    if: ${{ needs.run-jest-tests.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Split branch name
        env: 
          BRANCH: ${{ github.ref}}
        id: split
        run: echo "fragment=${BRANCH##*/}" > "$GITHUB_OUTPUT"
      - run: git checkout ${{ steps.split.outputs.fragment }} 
      - run: gh pr create --base main --title 'push request' --body 'pushing latest commit, unit tests successful'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  get-pull-request-number:
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.pr.outputs.pull_request_number }}
    needs: create-pull-request
    if: ${{ needs.create-pull-request.result == 'success' }}
    steps:
      - run: export GH_TOKEN=${{secrets.GH_TOKEN}}
      - run: echo "${{ secrets.GITHUB_TOKEN}}" | gh auth login --with-token
      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number)" > "$GITHUB_OUTPUT"
  approve:
    runs-on: ubuntu-latest
    needs: get-pull-request-number
    if: ${{ needs.create-pull-request.result == 'success'}}
    permissions:
      pull-requests: write
    steps:
      - name: print GH context
        run: echo '${{ toJSON(github) }}'
      - name: print outputs from previous job
        run: echo '${{ toJSON(needs) }}' 
        # .outputs.pull_request_number
        # env:
        #   GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - uses: hmarr/auto-approve-action@v3
      #   with:
      #     pull-request-number: ${{ needs.create-pull-request.outputs.pull_request_number}}
        
      # sdfdsfdsf