name: test-code
run-name: ${{ github.actor }} is testing his code
on: 
  push:
    branches-ignore:
      - main
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: npm install
      - run: npm run test
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.pr.outputs.test }}
      fragment: ${{ steps.split.outputs.test }}
    needs: [run-jest-tests]
    if: ${{ needs.run-jest-tests.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Split branch name
        env: 
          BRANCH: ${{ github.ref}}
        id: split
        run: echo "${BRANCH##*/}" > $GITHUB_OUTPUT
      - run: git checkout ${{ steps.split.outputs.fragment }} 
      - run: gh pr create --base main --title 'push request' --body 'pushing latest commit, unit tests successful'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Get Pull Request Number
        id: pr
        # run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        run: echo "$(gh pr view --json number -q .number || echo "")" > $GITHUB_OUTPUT
  approve:
    runs-on: ubuntu-latest
    needs: [ run-jest-tests, create-pull-request ]
    if: ${{ needs.run-jest-tests.result == 'success' && needs.create-pull-request.result == 'success'}}
    permissions:
      pull-requests: write
    steps:
      - name: test needs context
        run: echo ${{needs.create-pull-request.outputs.fragment}} 
        # .outputs.pull_request_number
        # env:
        #   GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - uses: hmarr/auto-approve-action@v3
      #   with:
      #     pull-request-number: ${{ needs.create-pull-request.outputs.pull_request_number}}
        
      